---
- name: Remove Git Package
  hosts: all
  become: true
  tasks:
    - name: Remove Git package
      apt:
        name: git
        state: absent

    - name: Remove Git configuration file
      file:
        path: ~/.gitconfig
        state: absent
