---
- hosts: all
  tasks:
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
  # Reboot after upgrade
    - name: Reboot host
      reboot:
